## Documentation: http://docs.travis-ci.com/user/languages/julia/
## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

dist: xenial

os:
  - linux
  
env:
  - JULIA_CMDSTAN_HOME="$HOME/cmdstan-2.19.1/"
  
julia:
  - 1.1
  
notifications:
  email: false
  
git:
  depth: 99999999
  
jobs:
  include:
    - stage: Test
      julia: 1.1
      os: linux
    - stage: Documentation
      julia: 1.1
      os: linux
      script:
        - julia --project=docs -e 'using Pkg; Pkg.instantiate(); Pkg.develop(PackageSpec(path=pwd()))'
        - julia --project=docs --color=yes docs/make.jl
      after_success: skip
